package com.nutrition.mx.enums;

public enum Permission {
	CITAS_CREAR, CITAS_VER, CITAS_EDITAR, PACIENTES_VER, PACIENTES_EDITAR, USUARIOS_CREAR, USUARIOS_VER, CLINICA_CREAR, CLINICA_EDITAR, CLINICA_VER
}
